server {
    listen 80;
    server_name yigitgulyurt.net.tr www.yigitgulyurt.net.tr;
    # Certbot HTTPS yüklemesinden sonra otomatik doldurulur

    location /static/ {
        alias /var/www/yigitgulyurt/app/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/yigitgulyurt/yigitgulyurt.sock;
    }
}
