"""add short_domain to qr_redirect

Revision ID: c7d0e4e3d146
Revises: 980df7061419
Create Date: 2026-05-02 14:31:46.147466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d0e4e3d146'
down_revision = '980df7061419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_redirect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_domain', sa.String(length=20), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_qr_redirect_short_domain'), ['short_domain'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_redirect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_redirect_short_domain'))
        batch_op.alter_column('id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('short_domain')

    # ### end Alembic commands ###
